### ISSUE TITLE
No rule to make target '/home/zlc/sat-modulo-symmetries/src/../cadical-master/build/libcadical.a'

### ISSUE THREAD

**Issue by lichengzhang1** [markirch/sat-modulo-symmetries#19]
I followed the requirements on website [sat-modulo-symmetries.readthedocs](https://sat-modulo-symmetries.readthedocs.io/en/latest/) and installed the prerequisite programs, but when I run "./build-and-install.sh," I encountered the following issue. I'm not sure what went wrong. Could it be that I didn't install cadical correctly? ( I run cadical --version, it shows 1.7.3)

```
-- Configuring done (4.4s)
-- Generating done (0.0s)
-- Build files have been written to: /home/zlc/sat-modulo-symmetries/build

-- build-and-install.sh: building SMS

make[2]: *** No rule to make target '/home/zlc/sat-modulo-symmetries/src/../cadical-master/build/libcadical.a', needed by 'src/smsd'.  Stop.
make[1]: *** [CMakeFiles/Makefile2:128: src/CMakeFiles/smsd.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make[2]: *** No rule to make target '/home/zlc/sat-modulo-symmetries/src/../cadical-master/build/libcadical.a', needed by 'src/smsg'.  Stop.
make[1]: *** [CMakeFiles/Makefile2:102: src/CMakeFiles/smsg.dir/all] Error 2
```

**Comment by lichengzhang1** [comment]
Thank you, I understand. I am externally compiling cadical,  so I can't find the corresponding directory.

**Comment by peitl** [comment]
Currently, the build script assumes that Cadical (with IPASIR-UP) is present and has been built in the directory `cadical-master` in the root directory; we should probably provide a way to download and build Cadical automatically as part of the build process in the future.

**Comment by lichengzhang1** [comment]
Nice. I also noticed that, and now I can run it successfully.
