### ISSUE TITLE
Compiling cadical requires -fPIC.

### ISSUE THREAD

**Issue by lichengzhang1** [markirch/sat-modulo-symmetries#25]
During compilation, I encountered the following error. Although I eventually resolved it, I'm documenting it here in hopes it may be useful to potential users.
```


/usr/sbin/ld: /mnt/e/z_graphtools/sat-modulo-symmetries-main_2024_04_08/sat-modulo-symmetries-main/src/../cadical/build/libcadical.a(solver.o): relocation R_X86_64_PC32 against symbol `stderr@@GLIBC_2.2.5' can not be used when making a shared object; recompile with -fPIC
/usr/sbin/ld: final link failed: bad value
/usr/sbin/ld: /mnt/e/z_graphtools/sat-modulo-symmetries-main_2024_04_08/sat-modulo-symmetries-main/src/../cadical/build/libcadical.a(solver.o): relocation R_X86_64_PC32 against symbol `stderr@@GLIBC_2.2.5' can not be used when making a shared object; recompile with -fPIC
/usr/sbin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
make[2]: *** [src/CMakeFiles/smsdir.dir/build.make:325: src/libsmsdir.so] Error 1
make[1]: *** [CMakeFiles/Makefile2:134: src/CMakeFiles/smsdir.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
collect2: error: ld returned 1 exit status
make[2]: *** [src/CMakeFiles/sms.dir/build.make:325: src/libsms.so] Error 1
make[1]: *** [CMakeFiles/Makefile2:108: src/CMakeFiles/sms.dir/all] Error 2
```

It appears that libcadical needs to be recompiled as position-independent code. We need to make some modifications in the cadical's makefile.in file: specifically, add `-fPIC` to the `CXXFLAGS=@CXXFLAGS@`.  （that is to say: `CXXFLAGS=@CXXFLAGS@ --fPIC`)

My  gcc version is 13.2.1 20230801 (GCC)

**Comment by peitl** [comment]
This issue should not arise when you run `./build-and-install.sh` afresh, it now also configures and builds Cadical with `-fPIC`. It can arise when you update an older version without reconfiguring an existing Cadical build, as probably happened to you (or if you build without `build-and-install.sh`). Glad you resolved it, thanks for sharing.

**Comment by lichengzhang1** [comment]
Yes, after visiting https://sat-modulo-symmetries.readthedocs.io/en/latest/, I went ahead and pre-compiled CaDiCaL. Perhaps your documentation could benefit from an update.
