### ISSUE TITLE
Is the -DEBUG option not working anymore?

### ISSUE THREAD

**Issue by lichengzhang1** [markirch/sat-modulo-symmetries#26]
Before, in [How to obtain graphs cleanly?](https://github.com/markirch/sat-modulo-symmetries/issues/22), [manfredscheucher](https://github.com/manfredscheucher)  told me that we can use --DEBUG 0 to only print the graph strings to stdout. 

However, in the new version, when I tried the command ` python -m pysms.graph_builder --vertices 7  --num-edges-low 10  --num-edges-upp 10  --all-graphs   --DEBUG 0`, it still outputs many additional information. I found the  file pysms.graph_builder, and the option hasn't been deleted. What could be the reason for this?

**Comment by peitl** [comment]
I think you forgot `--graph-format graph6`, then it should work as before.

You can also have a look at `pysms/solver.py`, it contains an alpha version of a proper Python-C++ SMS interface. You cannot pass configuration options right now, but it should otherwise be usable.
